In [5991]:
import pandas as pd

## Triplet Bert Related Eval Results

In [5992]:
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score

In [5993]:
# Triplet cos siamese bert

In [5994]:
df = pd.read_csv("../stance_code/Evaluation/bert_dummy_output/distance_concat_margin1_costriplet_cos_siamese_bs24_lr2e_5_epoch15_raw_score.csv")

In [5995]:
df

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
0,-4.223587,3.430138,0.020014,0.012879,1,0,1
1,4.980137,-5.918371,1.923178,0.001339,0,0,0
2,-4.051531,3.098645,0.004558,0.010478,1,1,1
3,-1.659985,2.563246,0.277413,0.157976,1,0,1
4,-1.103358,5.317815,0.293655,1.842567,1,1,1
...,...,...,...,...,...,...,...
2522,2.155837,-1.537567,1.053408,0.922337,0,0,0
2523,6.712749,-5.522651,1.332932,0.112898,0,0,0
2524,-2.778294,2.587539,0.518143,1.368011,1,1,1
2525,-3.157147,3.050995,0.483791,1.372143,1,1,1
2526,0.692743,0.942525,0.609729,0.659963,1,1,1

In [5996]:
#logits evaluation results

In [5997]:
f1_score(df.gold,df.predict_label)

0.8033536585365854

In [5998]:
precision_score(df.gold,df.predict_label)

0.8132716049382716

In [5999]:
recall_score(df.gold,df.predict_label)

0.7936746987951807

In [6000]:
#distance evaluation results

In [6001]:
f1_score(df.gold,df.distance_label)

0.7849223946784921

In [6002]:
precision_score(df.gold,df.distance_label)

0.7706821480406386

In [6003]:
recall_score(df.gold,df.distance_label)

0.7996987951807228

In [6004]:
#consistent cases (logtis prediction == distance prediction)

In [6005]:
df_consistency = df[df.predict_label==df.distance_label]

In [6006]:
df_consistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
1,4.980137,-5.918371,1.923178,0.001339,0,0,0
2,-4.051531,3.098645,0.004558,0.010478,1,1,1
4,-1.103358,5.317815,0.293655,1.842567,1,1,1
5,-2.957279,5.612340,0.010343,1.754936,1,1,1
6,-2.915035,5.855358,0.004241,1.868177,1,1,1
...,...,...,...,...,...,...,...
2522,2.155837,-1.537567,1.053408,0.922337,0,0,0
2523,6.712749,-5.522651,1.332932,0.112898,0,0,0
2524,-2.778294,2.587539,0.518143,1.368011,1,1,1
2525,-3.157147,3.050995,0.483791,1.372143,1,1,1
2526,0.692743,0.942525,0.609729,0.659963,1,1,1

In [6007]:
f1_score(df_consistency.gold,df_consistency.distance_label)

0.8353552859618716

In [6008]:
precision_score(df_consistency.gold,df_consistency.distance_label)

0.8253424657534246

In [6009]:
recall_score(df_consistency.gold,df_consistency.distance_label)

0.8456140350877193

In [6010]:
df_logits_diff = df_consistency[abs(df_consistency.undermine_score-df_consistency.support_score)>11.7]
df_logits_diff

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
56,-6.740227,6.935597,0.017248,1.656932,1,1,1
82,-6.699821,6.198657,0.017356,1.790910,1,1,1
176,7.776163,-5.735231,1.865803,0.175052,0,0,0
178,8.175444,-6.853647,1.905149,0.082175,0,0,0
179,7.822188,-5.983000,1.871615,0.071257,0,0,0
...,...,...,...,...,...,...,...
2516,7.405044,-6.452584,1.447262,0.201506,0,0,0
2517,6.648351,-6.019004,1.416802,0.236846,0,0,0
2518,6.778597,-5.306126,1.339745,0.412176,0,0,0
2520,7.552144,-6.467586,1.450673,0.491035,0,0,0
2523,6.712749,-5.522651,1.332932,0.112898,0,0,0

In [6011]:
f1_score(df_logits_diff.gold,df_logits_diff.distance_label)

0.8676470588235294

In [6012]:
precision_score(df_logits_diff.gold,df_logits_diff.distance_label)

0.9365079365079365

In [6013]:
recall_score(df_logits_diff.gold,df_logits_diff.distance_label)

0.8082191780821918

In [6014]:
df_distance_diff = df_consistency[abs(df_consistency.cp_distance-df_consistency.cop_distance)>1.9]
df_distance_diff

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
1,4.980137,-5.918371,1.923178,0.001339,0,0,0
14,4.973082,-5.446892,1.975014,0.038279,0,0,0
22,-2.595918,5.513531,0.011529,1.970146,1,1,1
27,-2.784658,5.825409,0.007447,1.957864,1,1,1
28,-2.574459,5.599093,0.028452,1.954338,1,1,1
...,...,...,...,...,...,...,...
2485,5.284534,-5.954888,1.962560,0.002266,0,0,0
2486,4.911831,-5.589746,1.951874,0.001502,0,0,0
2490,-2.891952,5.763986,0.001604,1.929383,1,1,1
2491,-2.285798,5.668227,0.008553,1.960932,1,1,1
2493,-2.277760,5.606550,0.010047,1.973817,1,1,1

In [6015]:
f1_score(df_distance_diff.gold,df_distance_diff.distance_label)

0.9526066350710901

In [6016]:
precision_score(df_distance_diff.gold,df_distance_diff.distance_label)

0.9262672811059908

In [6017]:
recall_score(df_distance_diff.gold,df_distance_diff.distance_label)

0.9804878048780488

In [6018]:
#inconsistent cases (logtis prediction != distance prediction)

In [6019]:
df_inconsistency = df

In [6020]:
df_consistency = df[df.predict_label==df.distance_label]

In [6021]:
df_inconsistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
0,-4.223587,3.430138,0.020014,0.012879,1,0,1
1,4.980137,-5.918371,1.923178,0.001339,0,0,0
2,-4.051531,3.098645,0.004558,0.010478,1,1,1
3,-1.659985,2.563246,0.277413,0.157976,1,0,1
4,-1.103358,5.317815,0.293655,1.842567,1,1,1
...,...,...,...,...,...,...,...
2522,2.155837,-1.537567,1.053408,0.922337,0,0,0
2523,6.712749,-5.522651,1.332932,0.112898,0,0,0
2524,-2.778294,2.587539,0.518143,1.368011,1,1,1
2525,-3.157147,3.050995,0.483791,1.372143,1,1,1
2526,0.692743,0.942525,0.609729,0.659963,1,1,1

In [6022]:
#triplet test set

In [6023]:
df_origin = pd.read_csv("../stance_code/Dataset/tri_test.tsv", delimiter="\t")

In [6024]:
#combine triplet test set with eval results

In [6025]:
incons_out = df_inconsistency.join(df_origin).drop("x",axis=1).drop("y",axis=1)

In [6026]:
# incons_out.to_csv("inconsistency_data.csv",index=False)

In [6027]:
# incons_out.to_excel("inconsistency_data.xlsx")

In [6028]:
accuracy_score(df_inconsistency.gold,df_inconsistency.predict_label)

0.7958053027305105

In [6029]:
# distance_correct_logits_wrong

In [6030]:
df_distance_correct_logits_wrong = df[(df.distance_label==df.gold)&(df.predict_label!=df.gold)]

In [6031]:
df_distance_correct_logits_wrong

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
59,6.975863,-2.372392,1.920776,1.928768,0,1,1
73,1.812300,-0.927047,1.096693,1.661179,0,1,1
78,2.363664,-1.478531,1.179334,1.422178,0,1,1
84,5.189340,-5.870834,1.708071,1.780854,0,1,1
110,-2.283030,2.307269,0.426038,0.200011,1,0,0
...,...,...,...,...,...,...,...
2434,-3.825589,5.084303,0.037229,0.004001,1,0,0
2465,4.006112,-1.870267,1.650200,1.766552,0,1,1
2473,1.276656,-1.107606,1.218479,1.468761,0,1,1
2480,-3.776413,2.909049,0.075312,0.017392,1,0,0
2513,0.033896,-0.449516,0.755636,1.142089,0,1,1

In [6032]:
# combine distance_correct_logits_wrong with test set

In [6033]:
dcorrect_lwrong_out = df_distance_correct_logits_wrong.join(df_origin).drop("x",axis=1).drop("y",axis=1)

In [6034]:
dcorrect_lwrong_out

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold,Label,claim,perspective,opposite_perspective
59,6.975863,-2.372392,1.920776,1.928768,0,1,1,1,Chess must be at the Olympics,"Chess is currently not an Olympic sport, but i...","Chess is currently an Olympic sport, but it sh..."
73,1.812300,-0.927047,1.096693,1.661179,0,1,1,1,Federal States are better than unitary nations,Citizens are better protected in federal states.,Citizens are not better protected in federal s...
78,2.363664,-1.478531,1.179334,1.422178,0,1,1,1,Federal States are better than unitary nations,Federal states are economically stronger,Federal states are not economically stronger
84,5.189340,-5.870834,1.708071,1.780854,0,1,1,1,The Catholic Church needs reform,"If priests were not forced to be celibate, the...","If priests were forced to be celibate, the iss..."
110,-2.283030,2.307269,0.426038,0.200011,1,0,0,0,College education is worth it,Many college graduates are employed in jobs th...,Many college graduates are employed in jobs th...
...,...,...,...,...,...,...,...,...,...,...,...
2434,-3.825589,5.084303,0.037229,0.004001,1,0,0,0,Democracies should ban the display of communis...,Extremist movements are harmful and should not...,Extremist movements are harmful and should be ...
2465,4.006112,-1.870267,1.650200,1.766552,0,1,1,1,The outcome of the Paris Climate Conference ne...,An international treaty will legalize non-comp...,An international treaty will not legalize non-...
2473,1.276656,-1.107606,1.218479,1.468761,0,1,1,1,The House of Lords should be reformed,The House of Lords is out of touch with the el...,The House of Lords is not out of touch with th...
2480,-3.776413,2.909049,0.075312,0.017392,1,0,0,0,NATO has succeeded in Afghanistan,the taliban is waiting and likley to regain co...,the taliban is not waiting and likley to regai...
2513,0.033896,-0.449516,0.755636,1.142089,0,1,1,1,Illegal downloaders should be cut off from the...,Internet access is an enabler of rights not a ...,Internet access is an enabler of rights a righ...

In [6035]:
# dcorrect_lwrong_out.to_csv("dcorrect_lwrong_data.csv")

In [6036]:
# dcorrect_lwrong_out.to_excel("dcorrect_lwrong_data.xlsx")

In [6037]:
#distance_wrong_logits_correct

In [6038]:
df_distance_wrong_logits_correct = df[(df.distance_label!=df.gold)&(df.predict_label==df.gold)]

In [6039]:
df_distance_wrong_logits_correct

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
0,-4.223587,3.430138,0.020014,0.012879,1,0,1
3,-1.659985,2.563246,0.277413,0.157976,1,0,1
81,-0.142597,0.318115,0.313459,0.120503,1,0,1
88,4.976699,-0.766726,1.319132,1.789118,0,1,0
101,6.664764,-2.338005,1.957810,1.962720,0,1,0
...,...,...,...,...,...,...,...
2428,1.780620,0.518181,0.962062,1.407790,0,1,0
2479,1.438328,0.848351,1.115165,1.629890,0,1,0
2503,0.627612,-0.557652,0.694943,1.455035,0,1,0
2506,2.762536,-1.856774,0.735328,0.786035,0,1,0
2521,3.317570,-3.755074,1.281456,1.372968,0,1,0

In [6040]:
#combine distance_wrong_logits_correct with test set

In [6041]:
dwrong_lcorrect_out = df_distance_wrong_logits_correct.join(df_origin).drop("x",axis=1).drop("y",axis=1)

In [6042]:
dwrong_lcorrect_out

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold,Label,claim,perspective,opposite_perspective
0,-4.223587,3.430138,0.020014,0.012879,1,0,1,1,School Day Should Be Extended,Lessons would feel less broken.,Lessons would not feel less broken.
3,-1.659985,2.563246,0.277413,0.157976,1,0,1,1,School Day Should Be Extended,Less need for homework.,More need for homework.
81,-0.142597,0.318115,0.313459,0.120503,1,0,1,1,The Catholic Church needs reform,The Catholic Church wants loyalty to instituti...,The Catholic Church wants loyalty to instituti...
88,4.976699,-0.766726,1.319132,1.789118,0,1,0,0,Positive Discrimination Towards Women in Socie...,"It is Men, Not Women, who are Disadvantaged in...","It is Men, Women, who are Disadvantaged in our..."
101,6.664764,-2.338005,1.957810,1.962720,0,1,0,0,Positive Discrimination Towards Women in Socie...,Positive discrimination takes away voters' fre...,negative discrimination takes away voters' fr...
...,...,...,...,...,...,...,...,...,...,...,...
2428,1.780620,0.518181,0.962062,1.407790,0,1,0,0,Democracies should ban the display of communis...,Society is ready to live with Nazi and Soviet ...,Society is not ready to live with Nazi and Sov...
2479,1.438328,0.848351,1.115165,1.629890,0,1,0,0,NATO has succeeded in Afghanistan,the taliban will likely resume their control o...,the taliban will not likely resume their contr...
2503,0.627612,-0.557652,0.694943,1.455035,0,1,0,0,Illegal downloaders should be cut off from the...,"File-sharing will still happen, despite these ...","File-sharing will not still happen, despite th..."
2506,2.762536,-1.856774,0.735328,0.786035,0,1,0,0,Illegal downloaders should be cut off from the...,Will file-sharing stop if downloaders are bann...,will not file-sharing stop if downloaders are...
2521,3.317570,-3.755074,1.281456,1.372968,0,1,0,0,Illegal downloaders should be cut off from the...,Human rights are infringed if internet use is ...,Human rights are not infringed if internet use...

In [6043]:
# dwrong_lcorrect_out.to_csv("dwrong_lcorrect_data.csv")

In [6044]:
# dwrong_lcorrect_out.to_excel("dwrong_lcorrect_data.xlsx")

In [6045]:
#dcorrect_lwrong_out cases

In [6046]:
dcorrect_lwrong_out

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold,Label,claim,perspective,opposite_perspective
59,6.975863,-2.372392,1.920776,1.928768,0,1,1,1,Chess must be at the Olympics,"Chess is currently not an Olympic sport, but i...","Chess is currently an Olympic sport, but it sh..."
73,1.812300,-0.927047,1.096693,1.661179,0,1,1,1,Federal States are better than unitary nations,Citizens are better protected in federal states.,Citizens are not better protected in federal s...
78,2.363664,-1.478531,1.179334,1.422178,0,1,1,1,Federal States are better than unitary nations,Federal states are economically stronger,Federal states are not economically stronger
84,5.189340,-5.870834,1.708071,1.780854,0,1,1,1,The Catholic Church needs reform,"If priests were not forced to be celibate, the...","If priests were forced to be celibate, the iss..."
110,-2.283030,2.307269,0.426038,0.200011,1,0,0,0,College education is worth it,Many college graduates are employed in jobs th...,Many college graduates are employed in jobs th...
...,...,...,...,...,...,...,...,...,...,...,...
2434,-3.825589,5.084303,0.037229,0.004001,1,0,0,0,Democracies should ban the display of communis...,Extremist movements are harmful and should not...,Extremist movements are harmful and should be ...
2465,4.006112,-1.870267,1.650200,1.766552,0,1,1,1,The outcome of the Paris Climate Conference ne...,An international treaty will legalize non-comp...,An international treaty will not legalize non-...
2473,1.276656,-1.107606,1.218479,1.468761,0,1,1,1,The House of Lords should be reformed,The House of Lords is out of touch with the el...,The House of Lords is not out of touch with th...
2480,-3.776413,2.909049,0.075312,0.017392,1,0,0,0,NATO has succeeded in Afghanistan,the taliban is waiting and likley to regain co...,the taliban is not waiting and likley to regai...
2513,0.033896,-0.449516,0.755636,1.142089,0,1,1,1,Illegal downloaders should be cut off from the...,Internet access is an enabler of rights not a ...,Internet access is an enabler of rights a righ...

In [6047]:
abs(dcorrect_lwrong_out.cp_distance-dcorrect_lwrong_out.cop_distance).median()

0.18335920000000006

In [6048]:
abs(dcorrect_lwrong_out.cp_distance-dcorrect_lwrong_out.cop_distance).mean()

0.24732256071492648

In [6049]:
abs(dcorrect_lwrong_out.cp_distance-dcorrect_lwrong_out.cop_distance).max()

1.0906459599999998

In [6050]:
abs(dcorrect_lwrong_out.cp_distance-dcorrect_lwrong_out.cop_distance).min()

0.0007354019999999996

In [6051]:
abs(dcorrect_lwrong_out.undermine_score-dcorrect_lwrong_out.support_score).median()

4.69863785

In [6052]:
abs(dcorrect_lwrong_out.undermine_score-dcorrect_lwrong_out.support_score).mean()

4.6868113829088225

In [6053]:
abs(dcorrect_lwrong_out.undermine_score-dcorrect_lwrong_out.support_score).max()

12.956747499999999

In [6054]:
abs(dcorrect_lwrong_out.undermine_score-dcorrect_lwrong_out.support_score).min()

0.009783112999999996

In [6055]:
#dwrong_lcorrect_out cases

In [6056]:
dwrong_lcorrect_out

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold,Label,claim,perspective,opposite_perspective
0,-4.223587,3.430138,0.020014,0.012879,1,0,1,1,School Day Should Be Extended,Lessons would feel less broken.,Lessons would not feel less broken.
3,-1.659985,2.563246,0.277413,0.157976,1,0,1,1,School Day Should Be Extended,Less need for homework.,More need for homework.
81,-0.142597,0.318115,0.313459,0.120503,1,0,1,1,The Catholic Church needs reform,The Catholic Church wants loyalty to instituti...,The Catholic Church wants loyalty to instituti...
88,4.976699,-0.766726,1.319132,1.789118,0,1,0,0,Positive Discrimination Towards Women in Socie...,"It is Men, Not Women, who are Disadvantaged in...","It is Men, Women, who are Disadvantaged in our..."
101,6.664764,-2.338005,1.957810,1.962720,0,1,0,0,Positive Discrimination Towards Women in Socie...,Positive discrimination takes away voters' fre...,negative discrimination takes away voters' fr...
...,...,...,...,...,...,...,...,...,...,...,...
2428,1.780620,0.518181,0.962062,1.407790,0,1,0,0,Democracies should ban the display of communis...,Society is ready to live with Nazi and Soviet ...,Society is not ready to live with Nazi and Sov...
2479,1.438328,0.848351,1.115165,1.629890,0,1,0,0,NATO has succeeded in Afghanistan,the taliban will likely resume their control o...,the taliban will not likely resume their contr...
2503,0.627612,-0.557652,0.694943,1.455035,0,1,0,0,Illegal downloaders should be cut off from the...,"File-sharing will still happen, despite these ...","File-sharing will not still happen, despite th..."
2506,2.762536,-1.856774,0.735328,0.786035,0,1,0,0,Illegal downloaders should be cut off from the...,Will file-sharing stop if downloaders are bann...,will not file-sharing stop if downloaders are...
2521,3.317570,-3.755074,1.281456,1.372968,0,1,0,0,Illegal downloaders should be cut off from the...,Human rights are infringed if internet use is ...,Human rights are not infringed if internet use...

In [6057]:
abs(dwrong_lcorrect_out.cp_distance-dwrong_lcorrect_out.cop_distance).median()

0.07489685000000001

In [6058]:
abs(dwrong_lcorrect_out.cp_distance-dwrong_lcorrect_out.cop_distance).mean()

0.16541975482742574

In [6059]:
abs(dwrong_lcorrect_out.cp_distance-dwrong_lcorrect_out.cop_distance).max()

1.0653685

In [6060]:
abs(dwrong_lcorrect_out.cp_distance-dwrong_lcorrect_out.cop_distance).min()

8.82149999999974e-06

In [6061]:
abs(dwrong_lcorrect_out.undermine_score-dwrong_lcorrect_out.support_score).median()

6.6984394499999995

In [6062]:
abs(dwrong_lcorrect_out.undermine_score-dwrong_lcorrect_out.support_score).mean()

6.3061969292425735

In [6063]:
abs(dwrong_lcorrect_out.undermine_score-dwrong_lcorrect_out.support_score).max()

18.714413999999998

In [6064]:
abs(dwrong_lcorrect_out.undermine_score-dwrong_lcorrect_out.support_score).min()

0.115963

In [6065]:
df_inconsistency[(abs(df_inconsistency.undermine_score-df_inconsistency.support_score)>7)&(abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance)<0.1)]

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
0,-4.223587,3.430138,0.020014,0.012879,1,0,1
2,-4.051531,3.098645,0.004558,0.010478,1,1,1
15,6.702568,-2.567696,1.940552,1.864902,0,0,0
16,6.727525,-2.691421,1.960978,1.921587,0,0,0
19,6.421700,-2.538338,1.935928,1.874516,0,0,0
...,...,...,...,...,...,...,...
2451,6.504695,-2.130013,1.908234,1.843760,0,0,0
2453,6.435262,-2.186800,1.926149,1.855757,0,0,0
2460,7.082847,-2.664161,1.979934,1.961441,0,0,0
2461,6.413897,-2.879239,1.971946,1.878633,0,0,0
2521,3.317570,-3.755074,1.281456,1.372968,0,1,0

In [6066]:
df_inconsistency[(abs(df_inconsistency.undermine_score-df_inconsistency.support_score)>7)&(abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance)<0.1)&(df_inconsistency.predict_label==df_inconsistency.gold)]

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
0,-4.223587,3.430138,0.020014,0.012879,1,0,1
2,-4.051531,3.098645,0.004558,0.010478,1,1,1
15,6.702568,-2.567696,1.940552,1.864902,0,0,0
16,6.727525,-2.691421,1.960978,1.921587,0,0,0
19,6.421700,-2.538338,1.935928,1.874516,0,0,0
...,...,...,...,...,...,...,...
2451,6.504695,-2.130013,1.908234,1.843760,0,0,0
2453,6.435262,-2.186800,1.926149,1.855757,0,0,0
2460,7.082847,-2.664161,1.979934,1.961441,0,0,0
2461,6.413897,-2.879239,1.971946,1.878633,0,0,0
2521,3.317570,-3.755074,1.281456,1.372968,0,1,0

In [6067]:
df_inconsistency[(abs(df_inconsistency.undermine_score-df_inconsistency.support_score)<3)&(abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance)>0.15)].count()

undermine_score    159
support_score      159
cp_distance        159
cop_distance       159
predict_label      159
distance_label     159
gold               159
dtype: int64

In [6068]:
df_inconsistency[(abs(df_inconsistency.undermine_score-df_inconsistency.support_score)<3)&(abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance)>0.15)&(df_inconsistency.distance_label==df_inconsistency.gold)].count()

undermine_score    104
support_score      104
cp_distance        104
cop_distance       104
predict_label      104
distance_label     104
gold               104
dtype: int64

In [6069]:
#consistent failed cases

In [6070]:
df_consistency[df_consistency.predict_label!=df_consistency.gold]

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
46,-2.267228,5.343608,0.012838,1.899688,1,1,0
51,5.155417,-4.237434,1.868408,0.744416,0,0,1
54,3.537244,-2.157459,1.688211,0.791399,0,0,1
63,-2.482541,5.729583,0.023178,1.951421,1,1,0
74,-3.022160,2.879174,0.396503,1.347344,1,1,0
...,...,...,...,...,...,...,...
2469,-2.194105,5.495428,0.036756,1.755904,1,1,0
2474,5.292336,-6.160551,1.813913,0.410568,0,0,1
2477,-0.591194,0.761670,0.984307,1.508494,1,1,0
2496,-2.799630,5.131019,0.060273,1.893408,1,1,0
2497,4.596515,-1.639086,1.612404,1.563472,0,0,1

In [6071]:
df_consistency_failed = df_consistency[df_consistency.predict_label!=df_consistency.gold]

In [6072]:
cons_out_failed = df_consistency_failed.join(df_origin).drop("x",axis=1).drop("y",axis=1)

In [6073]:
cons_out_failed

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold,Label,claim,perspective,opposite_perspective
46,-2.267228,5.343608,0.012838,1.899688,1,1,0,0,Make all museums free of charge,State funding should be used elsewhere,State funding should not be used elsewhere
51,5.155417,-4.237434,1.868408,0.744416,0,0,1,1,Make all museums free of charge,Museums are critical to the motivations as wel...,Museums are not critical to the motivations as...
54,3.537244,-2.157459,1.688211,0.791399,0,0,1,1,Make all museums free of charge,People are more likely to attend museums if th...,People are not more likely to attend museums i...
63,-2.482541,5.729583,0.023178,1.951421,1,1,0,0,Chess must be at the Olympics,Olympic sports are suppose to be physical,Olympic sports are not suppose to be physical
74,-3.022160,2.879174,0.396503,1.347344,1,1,0,0,Federal States are better than unitary nations,Federal States often have persistent losers.,Federal States often don't have persistent los...
...,...,...,...,...,...,...,...,...,...,...,...
2469,-2.194105,5.495428,0.036756,1.755904,1,1,0,0,The outcome of the Paris Climate Conference ne...,Allowing sovereign states to set and meet thei...,Allowing sovereign states not to set and meet ...
2474,5.292336,-6.160551,1.813913,0.410568,0,0,1,1,The House of Lords should be reformed,The House of Lords does not understand the nee...,The House of Lords does understand the needs o...
2477,-0.591194,0.761670,0.984307,1.508494,1,1,0,0,The House of Lords should be reformed,an apathetic public can be the cause of reform,an apathetic public can not be the cause of re...
2496,-2.799630,5.131019,0.060273,1.893408,1,1,0,0,Winning the Champions League Is Better Than Wi...,The Premiership is the most popular and succes...,The Premiership is not the most popular and su...
2497,4.596515,-1.639086,1.612404,1.563472,0,0,1,1,Winning the Champions League Is Better Than Wi...,Winning the Champions League relies more on lu...,Winning the Champions League relies less on lu...

In [6074]:
# cons_out_failed.to_csv("consistency_failed_data.csv")

In [6075]:
# cons_out_failed.to_excel("consistency_failed_data.xlsx")

In [6076]:
abs(cons_out_failed.cp_distance-cons_out_failed.cop_distance).median()

1.278518385

In [6077]:
abs(cons_out_failed.cp_distance-cons_out_failed.cop_distance).mean()

1.102007355244737

In [6078]:
abs(cons_out_failed.cp_distance-cons_out_failed.cop_distance).max()

1.9830208523

In [6079]:
abs(cons_out_failed.cp_distance-cons_out_failed.cop_distance).min()

0.0013897000000000492

In [6080]:
abs(cons_out_failed.undermine_score-cons_out_failed.support_score).median()

7.688840750000001

In [6081]:
abs(cons_out_failed.undermine_score-cons_out_failed.support_score).mean()

7.5094224646

In [6082]:
abs(cons_out_failed.undermine_score-cons_out_failed.support_score).max()

16.5979376

In [6083]:
abs(cons_out_failed.undermine_score-cons_out_failed.support_score).min()

0.08601858999999998

In [6084]:
df_consistency_correct = df_consistency[df_consistency.predict_label==df_consistency.gold]

In [6085]:
abs(df_consistency_correct.undermine_score-df_consistency_correct.support_score).median()

9.094334

In [6086]:
abs(df_consistency_correct.undermine_score-df_consistency_correct.support_score).mean()

9.707779702964732

In [6087]:
abs(df_consistency_correct.undermine_score-df_consistency_correct.support_score).max()

23.471

In [6088]:
abs(df_consistency_correct.undermine_score-df_consistency_correct.support_score).min()

0.018043279999999995

In [6089]:
abs(df_consistency_correct.cp_distance-df_consistency_correct.cop_distance).median()

1.6273515704000001

In [6090]:
abs(df_consistency_correct.cp_distance-df_consistency_correct.cop_distance).mean()

1.3397642599435988

In [6091]:
abs(df_consistency_correct.cp_distance-df_consistency_correct.cop_distance).max()

1.9834033666000002

In [6092]:
abs(df_consistency_correct.cp_distance-df_consistency_correct.cop_distance).min()

0.00021850000000001035

In [6093]:
#consistent cases

In [6094]:
df_consistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
1,4.980137,-5.918371,1.923178,0.001339,0,0,0
2,-4.051531,3.098645,0.004558,0.010478,1,1,1
4,-1.103358,5.317815,0.293655,1.842567,1,1,1
5,-2.957279,5.612340,0.010343,1.754936,1,1,1
6,-2.915035,5.855358,0.004241,1.868177,1,1,1
...,...,...,...,...,...,...,...
2522,2.155837,-1.537567,1.053408,0.922337,0,0,0
2523,6.712749,-5.522651,1.332932,0.112898,0,0,0
2524,-2.778294,2.587539,0.518143,1.368011,1,1,1
2525,-3.157147,3.050995,0.483791,1.372143,1,1,1
2526,0.692743,0.942525,0.609729,0.659963,1,1,1

In [6095]:
# df_consistency.to_csv("consistency_data.csv",index=False)

In [6096]:
# df_consistency.to_excel("consistency_data.xlsx",index=False)

In [6097]:
#consistent cases analysis

In [6098]:
consistent_logits_median = abs(df_consistency.undermine_score-df_consistency.support_score).median()
consistent_logits_median

8.884409999999999

In [6099]:
consistent_logits_mean = abs(df_consistency.undermine_score-df_consistency.support_score).mean()
consistent_logits_mean

9.326155330841113

In [6100]:
consistent_logits_max =abs(df_consistency.undermine_score-df_consistency.support_score).max()
consistent_logits_max

23.471

In [6101]:
consistent_logits_min = abs(df_consistency.undermine_score-df_consistency.support_score).min()
consistent_logits_min

0.018043279999999995

In [6102]:
consistent_distance_median = abs(df_consistency.cp_distance-df_consistency.cop_distance).median()
consistent_distance_median

1.5762243029999998

In [6103]:
consistent_distance_mean = abs(df_consistency.cp_distance-df_consistency.cop_distance).mean()
consistent_distance_mean

1.298490790877556

In [6104]:
consistent_distance_max = abs(df_consistency.cp_distance-df_consistency.cop_distance).max()
consistent_distance_max

1.9834033666000002

In [6105]:
consistent_distance_min = abs(df_consistency.cp_distance-df_consistency.cop_distance).min()
consistent_distance_min

0.00021850000000001035

In [6106]:
#inconsistent cases analysis

In [6107]:
inconsistent_logits_median = abs(df_inconsistency.undermine_score-df_inconsistency.support_score).median()
inconsistent_logits_median

8.583245699999999

In [6108]:
inconsistent_logits_mean = abs(df_inconsistency.undermine_score-df_inconsistency.support_score).mean()
inconsistent_logits_mean

8.835066144437594

In [6109]:
inconsistent_logits_max = abs(df_inconsistency.undermine_score-df_inconsistency.support_score).max()
inconsistent_logits_max

23.471

In [6110]:
inconsistent_logits_min = abs(df_inconsistency.undermine_score-df_inconsistency.support_score).min()
inconsistent_logits_min

0.009783112999999996

In [6111]:
inconsistent_distance_median = abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance).median()
inconsistent_distance_median

1.4037365

In [6112]:
inconsistent_distance_mean = abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance).mean()
inconsistent_distance_mean

1.1513442817425168

In [6113]:
inconsistent_distance_max = abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance).max()
inconsistent_distance_max

1.9834033666000002

In [6114]:
inconsistent_distance_min = abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance).min()
inconsistent_distance_min

8.82149999999974e-06

In [6115]:
# Use the "distance to median" to decide final prediction

In [6116]:
df_inconsistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
0,-4.223587,3.430138,0.020014,0.012879,1,0,1
1,4.980137,-5.918371,1.923178,0.001339,0,0,0
2,-4.051531,3.098645,0.004558,0.010478,1,1,1
3,-1.659985,2.563246,0.277413,0.157976,1,0,1
4,-1.103358,5.317815,0.293655,1.842567,1,1,1
...,...,...,...,...,...,...,...
2522,2.155837,-1.537567,1.053408,0.922337,0,0,0
2523,6.712749,-5.522651,1.332932,0.112898,0,0,0
2524,-2.778294,2.587539,0.518143,1.368011,1,1,1
2525,-3.157147,3.050995,0.483791,1.372143,1,1,1
2526,0.692743,0.942525,0.609729,0.659963,1,1,1

In [6117]:
dwrong_lcorrect_logits_median = abs(dwrong_lcorrect_out.undermine_score-dwrong_lcorrect_out.support_score).median()
dwrong_lcorrect_logits_mean = abs(dwrong_lcorrect_out.undermine_score-dwrong_lcorrect_out.support_score).mean()

In [6118]:
# dcorrect_lwrong_logits_median = abs(dcorrect_lwrong_out.undermine_score-dcorrect_lwrong_out.support_score).median()

In [6119]:
# dwrong_lcorrect_distance_median = abs(dwrong_lcorrect_out.cp_distance-dwrong_lcorrect_out.cop_distance).median()

In [6120]:
dcorrect_lwrong_distance_median = abs(dcorrect_lwrong_out.cp_distance-dcorrect_lwrong_out.cop_distance).median()
dcorrect_lwrong_distance_mean = abs(dcorrect_lwrong_out.cp_distance-dcorrect_lwrong_out.cop_distance).mean()

In [6121]:
distance_to_logits_median = abs(df_inconsistency.undermine_score-df_inconsistency.support_score)-inconsistent_logits_median
distance_to_logits_mean = abs(df_inconsistency.undermine_score-df_inconsistency.support_score)-inconsistent_logits_mean

In [6122]:
df_inconsistency["distance_to_logtis"] = (distance_to_logits_median-distance_to_logits_median.min())/(distance_to_logits_median.max()-distance_to_logits_median.min())

In [6123]:
# df_inconsistency["distance_to_logtis"] = (distance_to_logits_mean-distance_to_logits_mean.min())/(distance_to_logits_mean.max()-distance_to_logits_mean.min())

In [6124]:
distance_to_logits_median.max()

14.887754300000001

In [6125]:
distance_to_logits_mean.max()

14.635933855562406

In [6126]:
distance_to_distance_median = abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance)-inconsistent_distance_median
distance_to_distance_mean = abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance)-inconsistent_distance_mean

In [6127]:
(distance_to_distance_median-distance_to_distance_median.min())/(distance_to_distance_median.max()-distance_to_distance_median.min())

0       0.003593
1       0.968960
2       0.002980
3       0.060214
4       0.780935
          ...
2522    0.066080
2523    0.615120
2524    0.428487
2525    0.447891
2526    0.025323
Length: 2527, dtype: float64

In [6128]:
(distance_to_distance_median.max()-distance_to_distance_median.min())

1.9833945451000001

In [6129]:
(distance_to_distance_mean-distance_to_distance_mean.min())/(distance_to_distance_mean.max()-distance_to_distance_mean.min())

0       0.003593
1       0.968960
2       0.002980
3       0.060214
4       0.780935
          ...
2522    0.066080
2523    0.615120
2524    0.428487
2525    0.447891
2526    0.025323
Length: 2527, dtype: float64

In [6130]:
df_inconsistency["distance_to_distance"] = (distance_to_distance_median-distance_to_distance_median.min())/(distance_to_distance_median.max()-distance_to_distance_median.min())

In [6131]:
# df_inconsistency["distance_to_distance"] = (distance_to_distance_mean-distance_to_distance_mean.min())/(distance_to_distance_mean.max()-distance_to_distance_mean.min())

In [6132]:
df_inconsistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold,distance_to_logtis,distance_to_distance
0,-4.223587,3.430138,0.020014,0.012879,1,0,1,0.325812,0.003593
1,4.980137,-5.918371,1.923178,0.001339,0,0,0,0.464116,0.968960
2,-4.051531,3.098645,0.004558,0.010478,1,1,1,0.304349,0.002980
3,-1.659985,2.563246,0.277413,0.157976,1,0,1,0.179592,0.060214
4,-1.103358,5.317815,0.293655,1.842567,1,1,1,0.273276,0.780935
...,...,...,...,...,...,...,...,...,...
2522,2.155837,-1.537567,1.053408,0.922337,0,0,0,0.157009,0.066080
2523,6.712749,-5.522651,1.332932,0.112898,0,0,0,0.521099,0.615120
2524,-2.778294,2.587539,0.518143,1.368011,1,1,1,0.228294,0.428487
2525,-3.157147,3.050995,0.483791,1.372143,1,1,1,0.264196,0.447891
2526,0.692743,0.942525,0.609729,0.659963,1,1,1,0.010230,0.025323

In [6133]:
df_consistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
1,4.980137,-5.918371,1.923178,0.001339,0,0,0
2,-4.051531,3.098645,0.004558,0.010478,1,1,1
4,-1.103358,5.317815,0.293655,1.842567,1,1,1
5,-2.957279,5.612340,0.010343,1.754936,1,1,1
6,-2.915035,5.855358,0.004241,1.868177,1,1,1
...,...,...,...,...,...,...,...
2522,2.155837,-1.537567,1.053408,0.922337,0,0,0
2523,6.712749,-5.522651,1.332932,0.112898,0,0,0
2524,-2.778294,2.587539,0.518143,1.368011,1,1,1
2525,-3.157147,3.050995,0.483791,1.372143,1,1,1
2526,0.692743,0.942525,0.609729,0.659963,1,1,1

In [6134]:
import flyingsquid
from numpy.random import seed, rand
import itertools
import numpy as np

In [6135]:
df_inconsistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold,distance_to_logtis,distance_to_distance
0,-4.223587,3.430138,0.020014,0.012879,1,0,1,0.325812,0.003593
1,4.980137,-5.918371,1.923178,0.001339,0,0,0,0.464116,0.968960
2,-4.051531,3.098645,0.004558,0.010478,1,1,1,0.304349,0.002980
3,-1.659985,2.563246,0.277413,0.157976,1,0,1,0.179592,0.060214
4,-1.103358,5.317815,0.293655,1.842567,1,1,1,0.273276,0.780935
...,...,...,...,...,...,...,...,...,...
2522,2.155837,-1.537567,1.053408,0.922337,0,0,0,0.157009,0.066080
2523,6.712749,-5.522651,1.332932,0.112898,0,0,0,0.521099,0.615120
2524,-2.778294,2.587539,0.518143,1.368011,1,1,1,0.228294,0.428487
2525,-3.157147,3.050995,0.483791,1.372143,1,1,1,0.264196,0.447891
2526,0.692743,0.942525,0.609729,0.659963,1,1,1,0.010230,0.025323

In [6136]:
df_inconsistency[abs(df_inconsistency.undermine_score-df_inconsistency.support_score)<9.7]

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold,distance_to_logtis,distance_to_distance
0,-4.223587,3.430138,0.020014,0.012879,1,0,1,0.325812,0.003593
2,-4.051531,3.098645,0.004558,0.010478,1,1,1,0.304349,0.002980
3,-1.659985,2.563246,0.277413,0.157976,1,0,1,0.179592,0.060214
4,-1.103358,5.317815,0.293655,1.842567,1,1,1,0.273276,0.780935
5,-2.957279,5.612340,0.010343,1.754936,1,1,1,0.364850,0.879595
...,...,...,...,...,...,...,...,...,...
2521,3.317570,-3.755074,1.281456,1.372968,0,1,0,0.301044,0.046134
2522,2.155837,-1.537567,1.053408,0.922337,0,0,0,0.157009,0.066080
2524,-2.778294,2.587539,0.518143,1.368011,1,1,1,0.228294,0.428487
2525,-3.157147,3.050995,0.483791,1.372143,1,1,1,0.264196,0.447891
2526,0.692743,0.942525,0.609729,0.659963,1,1,1,0.010230,0.025323

In [6137]:
df_inconsistency["snorkel_logits_17"]=df_inconsistency.predict_label
df_inconsistency.snorkel_logits_17=df_inconsistency.apply(lambda x: -1 if x.snorkel_logits_17==0 else 1, axis=1)
df_inconsistency.snorkel_logits_17=df_inconsistency.apply(lambda x: 0 if abs(x.undermine_score-x.support_score)<1.7  else x.snorkel_logits_17, axis=1)

In [6138]:
df_inconsistency["snorkel_logits_37"]=df_inconsistency.predict_label
df_inconsistency.snorkel_logits_37=df_inconsistency.apply(lambda x: -1 if x.snorkel_logits_37==0 else 1, axis=1)
df_inconsistency.snorkel_logits_37=df_inconsistency.apply(lambda x: 0 if abs(x.undermine_score-x.support_score)<3.7  else x.snorkel_logits_37, axis=1)

In [6139]:
df_inconsistency["snorkel_logits_57"]=df_inconsistency.predict_label
df_inconsistency.snorkel_logits_57=df_inconsistency.apply(lambda x: -1 if x.snorkel_logits_57==0 else 1, axis=1)
df_inconsistency.snorkel_logits_57=df_inconsistency.apply(lambda x: 0 if abs(x.undermine_score-x.support_score)<5.7  else x.snorkel_logits_57, axis=1)

In [6140]:
df_inconsistency["snorkel_logits_77"]=df_inconsistency.predict_label
df_inconsistency.snorkel_logits_77=df_inconsistency.apply(lambda x: -1 if x.snorkel_logits_77==0 else 1, axis=1)
df_inconsistency.snorkel_logits_77=df_inconsistency.apply(lambda x: 0 if abs(x.undermine_score-x.support_score)<7.7  else x.snorkel_logits_77, axis=1)

In [6141]:
df_inconsistency["snorkel_logits_97"]=df_inconsistency.predict_label
df_inconsistency.snorkel_logits_97=df_inconsistency.apply(lambda x: -1 if x.snorkel_logits_97==0 else 1, axis=1)
df_inconsistency.snorkel_logits_97=df_inconsistency.apply(lambda x: 0 if abs(x.undermine_score-x.support_score)<9.7  else x.snorkel_logits_97, axis=1)

In [6142]:
df_inconsistency["snorkel_distance_01"]=df_inconsistency.distance_label
df_inconsistency.snorkel_distance_01=df_inconsistency.apply(lambda x: -1 if x.snorkel_distance_01==0 else 1, axis=1)
df_inconsistency.snorkel_distance_01=df_inconsistency.apply(lambda x: 0 if abs(x.cp_distance-x.cop_distance)<0.1  else x.snorkel_distance_01, axis=1)

In [6143]:
df_inconsistency["snorkel_distance_03"]=df_inconsistency.distance_label
df_inconsistency.snorkel_distance_03=df_inconsistency.apply(lambda x: -1 if x.snorkel_distance_03==0 else 1, axis=1)
df_inconsistency.snorkel_distance_03=df_inconsistency.apply(lambda x: 0 if abs(x.cp_distance-x.cop_distance)<0.3  else x.snorkel_distance_03, axis=1)

In [6144]:
df_inconsistency["snorkel_distance_05"]=df_inconsistency.distance_label
df_inconsistency.snorkel_distance_05=df_inconsistency.apply(lambda x: -1 if x.snorkel_distance_05==0 else 1, axis=1)
df_inconsistency.snorkel_distance_05=df_inconsistency.apply(lambda x: 0 if abs(x.cp_distance-x.cop_distance)<0.5  else x.snorkel_distance_05, axis=1)

In [6145]:
df_inconsistency["snorkel_distance_07"]=df_inconsistency.distance_label
df_inconsistency.snorkel_distance_07=df_inconsistency.apply(lambda x: -1 if x.snorkel_distance_07==0 else 1, axis=1)
df_inconsistency.snorkel_distance_07=df_inconsistency.apply(lambda x: 0 if abs(x.cp_distance-x.cop_distance)<0.7  else x.snorkel_distance_07, axis=1)

In [6146]:
df_inconsistency["snorkel_distance_09"]=df_inconsistency.distance_label
df_inconsistency.snorkel_distance_09=df_inconsistency.apply(lambda x: -1 if x.snorkel_distance_09==0 else 1, axis=1)
df_inconsistency.snorkel_distance_09=df_inconsistency.apply(lambda x: 0 if abs(x.cp_distance-x.cop_distance)<0.9  else x.snorkel_distance_09, axis=1)

In [6147]:
df_inconsistency["snorkel_label"]=df_inconsistency.gold
df_inconsistency.snorkel_label = df_inconsistency.apply(lambda x: -1 if x.snorkel_label==0 else 1, axis=1)

In [6148]:
df_inconsistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold,distance_to_logtis,distance_to_distance,snorkel_logits_17,snorkel_logits_37,snorkel_logits_57,snorkel_logits_77,snorkel_logits_97,snorkel_distance_01,snorkel_distance_03,snorkel_distance_05,snorkel_distance_07,snorkel_distance_09,snorkel_label
0,-4.223587,3.430138,0.020014,0.012879,1,0,1,0.325812,0.003593,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,4.980137,-5.918371,1.923178,0.001339,0,0,0,0.464116,0.968960,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1
2,-4.051531,3.098645,0.004558,0.010478,1,1,1,0.304349,0.002980,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,-1.659985,2.563246,0.277413,0.157976,1,0,1,0.179592,0.060214,1.0,1.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,1
4,-1.103358,5.317815,0.293655,1.842567,1,1,1,0.273276,0.780935,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2522,2.155837,-1.537567,1.053408,0.922337,0,0,0,0.157009,0.066080,-1.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,-1
2523,6.712749,-5.522651,1.332932,0.112898,0,0,0,0.521099,0.615120,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1
2524,-2.778294,2.587539,0.518143,1.368011,1,1,1,0.228294,0.428487,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1
2525,-3.157147,3.050995,0.483791,1.372143,1,1,1,0.264196,0.447891,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1
2526,0.692743,0.942525,0.609729,0.659963,1,1,1,0.010230,0.025323,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [6149]:
df_inconsistency.iloc[:,-10:]

,snorkel_logits_37,snorkel_logits_57,snorkel_logits_77,snorkel_logits_97,snorkel_distance_01,snorkel_distance_03,snorkel_distance_05,snorkel_distance_07,snorkel_distance_09,snorkel_label
0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1
2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,1.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,1
4,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...
2522,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,-1
2523,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1
2524,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1
2525,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1
2526,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [6150]:
df_inconsistency.iloc[:,-10:].values

array([[ 1.,  1.,  0., ...,  0.,  0.,  1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [ 1.,  1.,  0., ...,  0.,  0.,  1.],
       ...,
       [ 1.,  0.,  0., ...,  1.,  0.,  1.],
       [ 1.,  1.,  0., ...,  1.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [6151]:
df_inconsistency.snorkel_label.values

array([ 1, -1,  1, ...,  1,  1,  1], dtype=int64)

In [6152]:
L_dev = df_inconsistency.iloc[:,-10:].values

In [6153]:
Y_dev = df_inconsistency.snorkel_label.values

In [6154]:
df_L_train = pd.read_csv("../stance_code_local/finetuned_L_train_entiretest.csv")

In [6155]:
df_L_train.iloc[:,-11:]

,snorkel_logits_17,snorkel_logits_37,snorkel_logits_57,snorkel_logits_77,snorkel_logits_97,snorkel_distance_01,snorkel_distance_03,snorkel_distance_05,snorkel_distance_07,snorkel_distance_09,snorkel_label
0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,-1.0,-1.0,-1.0,-1.0,0.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1
2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...
2522,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1
2523,-1.0,-1.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0,0.0,0.0,-1
2524,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1
2525,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1
2526,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [6156]:
df_L_train.iloc[:,-11:].values

array([[ 1.,  1.,  0., ...,  0.,  0.,  1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [ 1.,  1.,  0., ...,  0.,  0.,  1.],
       ...,
       [ 1.,  0.,  0., ...,  0.,  0.,  1.],
       [ 1.,  1.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [6157]:
L_train = df_L_train.iloc[:,-11:].values

In [6158]:
from flyingsquid.label_model import LabelModel

In [6159]:
m = 10

label_model = LabelModel(m)

In [6160]:
label_model.fit(L_train)

In [6161]:
preds = label_model.predict(L_dev).reshape(Y_dev.shape)
accuracy = np.sum(preds == Y_dev) / Y_dev.shape[0]

# print('Label model accuracy: {}%'.format(int(100 * accuracy)))
f1_score(Y_dev,preds)

0.8530701754385964

In [6166]:
majority_vote_preds = np.array([1 if pred > 0 else -1 for pred in np.sum(L_dev, axis=1)])
majority_vote_accuracy = np.sum(majority_vote_preds == Y_dev) / Y_dev.shape[0]

# print('Majority vote accuracy: {}%'.format(int(100 * majority_vote_accuracy)))
f1_score(Y_dev,majority_vote_preds)

0.8293963254593176

In [6167]:
df_inconsistency["snorkel_predict"] = preds
df_inconsistency.snorkel_predict=df_inconsistency.apply(lambda x: 0 if x.snorkel_predict==-1 else 1, axis=1)

In [6168]:
df_inconsistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold,distance_to_logtis,distance_to_distance,snorkel_logits_17,...,snorkel_logits_57,snorkel_logits_77,snorkel_logits_97,snorkel_distance_01,snorkel_distance_03,snorkel_distance_05,snorkel_distance_07,snorkel_distance_09,snorkel_label,snorkel_predict
0,-4.223587,3.430138,0.020014,0.012879,1,0,1,0.325812,0.003593,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
1,4.980137,-5.918371,1.923178,0.001339,0,0,0,0.464116,0.968960,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,0
2,-4.051531,3.098645,0.004558,0.010478,1,1,1,0.304349,0.002980,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
3,-1.659985,2.563246,0.277413,0.157976,1,0,1,0.179592,0.060214,1.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,1,1
4,-1.103358,5.317815,0.293655,1.842567,1,1,1,0.273276,0.780935,1.0,...,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2522,2.155837,-1.537567,1.053408,0.922337,0,0,0,0.157009,0.066080,-1.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,-1,0
2523,6.712749,-5.522651,1.332932,0.112898,0,0,0,0.521099,0.615120,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,0
2524,-2.778294,2.587539,0.518143,1.368011,1,1,1,0.228294,0.428487,1.0,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1,1
2525,-3.157147,3.050995,0.483791,1.372143,1,1,1,0.264196,0.447891,1.0,...,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1,1
2526,0.692743,0.942525,0.609729,0.659963,1,1,1,0.010230,0.025323,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1

In [6174]:
f1_score(df_inconsistency.gold,df_inconsistency.snorkel_predict)

0.8530701754385964

In [6191]:
precision_score(df_inconsistency.gold,df_inconsistency.snorkel_predict)

0.8288352272727273

In [6192]:
recall_score(df_inconsistency.gold,df_inconsistency.snorkel_predict)

0.8787650602409639